//
//  Globals.swift
//  FRC Scout
//
//  Created by Louie Bertoncin on 2/12/15.
//  Copyright (c) 2015 David Swed. All rights reserved.
//

import UIKit

let SWIPECONFIRMKEY = "SwipeConfrimed"
let WEEKSELECTEDKEY = "WeekSelected"
let REGIONALSELECTEDKEY = "RegionalSelected"

let scoutPositions = [
    "Red 1",
    "Red 2",
    "Red 3",
    "Blue 1",
    "Blue 2",
    "Blue 3"]

let week1Regionals = [
    "South Florida Regional",
    "Lake Superior Regional",
    "Northern Lights Regional",
    "Palmetto Regional",
    "Dallas Regional",
    "Inland Empire Regional",
    "Georgia Southern Classic Regional",
    "FIM District - Howell Event",
    "FIM District - Southfield Event",
    "FIM District - Standish Event",
    "NE District - Granite State Event",
    "PNW District - Oregon City Event",
    "PNW District - Auburn Mountainview Event",
    "NE District - Waterbury Event",
    "IN District - Indianapolis Event",
    "MAR District - Hatboro-Horsham Event"]

let week2Regionals = [
    "Greater Toronto Central Regional",
    "Mexico City Regional",
    "Arkansas Rock City Regional",
    "Greater Pittsburgh Regional",
    "Central Valley Regional",
    "NE District - Pioneer Valley Event",
    "FIM District - Kettering University Event",
    "FIM District - Kentwood Event",
    "FIM District - Waterford Event",
    "PNW District - West Valley Event",
    "NE District - Reading Event",
    "MAR District - Mt. Olive Event",
    "PNW District - Glacier Peak Event",]

let week3Regionals = [
    "Israel Regional",
    "Australia Regional",
    "Greater Toronto East Regional",
    "Los Angeles Regional sponsored by The Roddenberry Foundation",
    "Orlando Regional",
    "Greater Kansas City Regional",
    "Alamo Regional sponsored by Rackspace Hosting",
    "Utah Regional",
    "New York City Regional",
    "IN District - Kokomo City of Firsts Event sponsored by AndyMark",
    "NE District - UMass - Dartmouth Event",
    "NE District - Pine Tree Event",
    "FIM District - Woodhaven Event",
    "FIM District - Gull Lake Event",
    "FIM District - Traverse City Event",
    "PNW District - Wilsonville Event",
    "MAR District - Springside Chestnut Hill Event",
    "PNW District - Mount Vernon Event"]

let week4Regionals = [
    "Waterloo Regional",
    "FRC Festival de Robotique - Montreal Regional",
    "Arizona East Regional",
    "Sacramento Regional",
    "Central Illinois Regional",
    "Bayou Regional",
    "St. Louis Regional",
    "North Carolina Regional",
    "New York Tech Valley Regional",
    "Virginia Regional",
    "Wisconsin Regional",
    "IN District - Purdue Event",
    "FIM District - West Michigan Event",
    "FIM District - Great Lakes Bay Region Event",
    "FIM District - St. Joseph Event",
    "PNW District - Central Washington University Event",
    "NE District - UNH Event",
    "MAR District - Seneca Event",
    "NE District - Rhode Island Event",
    "PNW District - Shorewood Event"]

let week5Regionals = [
    "North Bay Regional",
    "Colorado Regional",
    "Peachtree Regional",
    "Hawaii Regional",
    "Las Vegas Regional",
    "SBPLI Long Island Regional",
    "Finger Lakes Regional",
    "Buckeye Regional",
    "Oklahoma Regional",
    "Hub City Regional",
    "Greater DC Regional",
    "Ventura Regional",
    "NE District - Northeastern University Event",
    "FIM District - Center Line Event",
    "FIM District - Escanaba Event",
    "FIM District - Livonia Event",
    "PNW District - Philomath Event",
    "PNW District - Auburn Event",
    "NE District - Hartford Event",
    "MAR District - Bridgewater-Raritan Event",
    "MAR District - Upper Darby Event"]

let week6Regionals = [
    "Western Canada Regional",
    "Windsor Essex Great Lakes Regional",
    "Arizona West Regional",
    "San Diego Regional",
    "Silicon Valley Regional",
    "Midwest Regional",
    "Chesapeake Regional",
    "Minnesota 10000 Lakes Regional",
    "Minnesota North Star Regional",
    "Queen City Regional",
    "Smoky Mountains Regional",
    "Lone Star Regional",
    "Pacific Northwest District Championship",
    "Indiana FIRST District Championship",
    "FIM District - Lansing Event",
    "FIM District - Bedford Event",
    "FIM District - Troy Event",
    "MAR District - North Brunswick Event"]

let week7Reginals = [
    "NE FIRST District Championship presented by United Technologies",
    "FIRST in Michigan District Championship",
    "Mid-Atlantic Robotics District Championship",
    "FIRST Championship"]

let allRegionalsArray = [
    "South Florida Regional",
    "Lake Superior Regional",
    "Northern Lights Regional",
    "Palmetto Regional",
    "Dallas Regional",
    "Inland Empire Regional",
    "Georgia Southern Classic Regional",
    "FIM District - Howell Event",
    "FIM District - Southfield Event",
    "FIM District - Standish Event",
    "NE District - Granite State Event",
    "PNW District - Oregon City Event",
    "PNW District - Auburn Mountainview Event",
    "NE District - Waterbury Event",
    "IN District - Indianapolis Event",
    "MAR District - Hatboro-Horsham Event",
    "Greater Toronto Central Regional",
    "Mexico City Regional",
    "Arkansas Rock City Regional",
    "Greater Pittsburgh Regional",
    "Central Valley Regional",
    "NE District - Pioneer Valley Event",
    "FIM District - Kettering University Event",
    "FIM District - Kentwood Event",
    "FIM District - Waterford Event",
    "PNW District - West Valley Event",
    "NE District - Reading Event",
    "MAR District - Mt. Olive Event",
    "PNW District - Glacier Peak Event",
    "Australia Regional",
    "Greater Toronto East Regional",
    "Los Angeles Regional sponsored by The Roddenberry Foundation",
    "Orlando Regional",
    "Greater Kansas City Regional",
    "Alamo Regional sponsored by Rackspace Hosting",
    "Utah Regional",
    "New York City Regional",
    "IN District - Kokomo City of Firsts Event sponsored by AndyMark",
    "NE District - UMass - Dartmouth Event",
    "NE District - Pine Tree Event",
    "FIM District - Woodhaven Event",
    "FIM District - Gull Lake Event",
    "FIM District - Traverse City Event",
    "PNW District - Wilsonville Event",
    "MAR District - Springside Chestnut Hill Event",
    "PNW District - Mount Vernon Event",
    "Waterloo Regional",
    "FRC Festival de Robotique - Montreal Regional",
    "Arizona East Regional",
    "Sacramento Regional",
    "Central Illinois Regional",
    "Bayou Regional",
    "St. Louis Regional",
    "North Carolina Regional",
    "New York Tech Valley Regional",
    "Virginia Regional",
    "Wisconsin Regional",
    "IN District - Purdue Event",
    "FIM District - West Michigan Event",
    "FIM District - Great Lakes Bay Region Event",
    "FIM District - St. Joseph Event",
    "PNW District - Central Washington University Event",
    "NE District - UNH Event",
    "MAR District - Seneca Event",
    "NE District - Rhode Island Event",
    "PNW District - Shorewood Event","North Bay Regional",
    "Colorado Regional",
    "Peachtree Regional",
    "Hawaii Regional",
    "Las Vegas Regional",
    "SBPLI Long Island Regional",
    "Finger Lakes Regional",
    "Buckeye Regional",
    "Oklahoma Regional",
    "Hub City Regional",
    "Greater DC Regional",
    "Ventura Regional",
    "NE District - Northeastern University Event",
    "FIM District - Center Line Event",
    "FIM District - Escanaba Event",
    "FIM District - Livonia Event",
    "PNW District - Philomath Event",
    "PNW District - Auburn Event",
    "NE District - Hartford Event",
    "MAR District - Bridgewater-Raritan Event",
    "MAR District - Upper Darby Event",
    "Western Canada Regional",
    "Windsor Essex Great Lakes Regional",
    "Arizona West Regional",
    "San Diego Regional",
    "Silicon Valley Regional",
    "Midwest Regional",
    "Chesapeake Regional",
    "Minnesota 10000 Lakes Regional",
    "Minnesota North Star Regional",
    "Queen City Regional",
    "Smoky Mountains Regional",
    "Lone Star Regional",
    "Pacific Northwest District Championship",
    "Indiana FIRST District Championship",
    "FIM District - Lansing Event",
    "FIM District - Bedford Event",
    "FIM District - Troy Event",
    "MAR District - North Brunswick Event",
    "NE FIRST District Championship presented by United Technologies",
    "FIRST in Michigan District Championship",
    "Mid-Atlantic Robotics District Championship",
    "FIRST Championship"]

let allWeekRegionals = [allRegionalsArray, week1Regionals, week2Regionals, week3Regionals, week4Regionals, week5Regionals, week6Regionals, week7Reginals]

